language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  - npm install -g bower
  - npm install -g grunt-cli
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script:
  - vendor/bin/phpspec run
